# Generated by Django 4.0.5 on 2022-06-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisionRules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='decisionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Eva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('decision', models.CharField(max_length=250)),
                ('row', models.CharField(max_length=250)),
            ],
        ),
    ]
