# Generated by Django 4.0.5 on 2022-06-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisionRules', '0003_rename_attribute_eva_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eva',
            name='attributes',
        ),
        migrations.AddField(
            model_name='eva',
            name='attribute',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
